language: cpp

notifications:
  email: false
  
sudo: required

os:
  - linux
  - osx

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi
  
  - if [[ $OSX ]]; then brew update; fi

  - export LEPT_VER=1.73

install:
  - if [[ $OSX ]]; then brew install icu4c pango; brew link --force gettext; fi
  - if [[ $OSX ]]; then export ICU_ROOT=/usr/local/opt/icu4c ; fi
  - wget --no-check-certificate https://www.cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.sh
  - sudo sh cmake-3.4.1-Linux-x86_64.sh --skip-license --prefix=/usr
  - wget -O leptonica.zip https://github.com/DanBloomberg/leptonica/archive/v$LEPT_VER.zip
  - unzip leptonica.zip -d .
  - cmake -Hleptonica-$LEPT_VER -Bleptonica-$LEPT_VER/build
  - make -C leptonica-$LEPT_VER/build
  - if [[ $LINUX && "$CXX" = "g++" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DLeptonica_DIR=leptonica-$LEPT_VER/build
  - make
