# Travis CI configuration for Tesseract
sudo: false
notifications:
  email: false
language: cpp

os: linux
dist: focal
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
compiler:
  - gcc
  - clang
env:
  - LEPT_VER=1.80.0
cache:
  directories:
    - leptonica-$LEPT_VER

before_install:
  - sudo apt-get install libpango1.0-dev libicu-dev -y
  
install:
  - if test ! -d leptonica-$LEPT_VER/src; then curl -Ls https://github.com/DanBloomberg/leptonica/archive/$LEPT_VER.tar.gz | tar -xz; fi
  - if test ! -d leptonica-$LEPT_VER/usr; then cmake -Hleptonica-$LEPT_VER -Bleptonica-$LEPT_VER/build -DCMAKE_INSTALL_PREFIX=leptonica-$LEPT_VER/usr; fi
  - if test ! -e leptonica-$LEPT_VER/usr/lib/libleptonica.so; then make -C leptonica-$LEPT_VER/build install; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DLeptonica_DIR=leptonica-$LEPT_VER/build -DSW_BUILD=OFF
  - make
  - sudo make install

after_script:
  - tesseract -v
  - text2image -v
  - lstmtraining -v
  - ls /home/travis/build/tesseract-ocr/tesseract/test/testing/*.tif
  - wget https://github.com/egorpugin/tessdata/raw/master/tessdata/eng.traineddata
  - tesseract /home/travis/build/tesseract-ocr/tesseract/test/testing/phototest.tif - -l eng --tessdata-dir ./
