os: Visual Studio 2017

platform:
  - Win32
  - Win64
  
cache:
  - c:/Users/appveyor/.cppan/storage

configuration:
  - Release  
  
# for curl
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

before_build:
  - if %platform%==Win32 set generator=Visual Studio 15 2017
  - if %platform%==Win64 set generator=Visual Studio 15 2017 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64

  - curl -fsS -L -o cppan.zip https://cppan.org/client/cppan-master-Windows-client.zip
  - 7z x cppan.zip
  - set PATH=%PATH%;%cd%

  - cppan # dummy run to create %USERPROFILE%\.cppan\cppan.yml
  - ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nvar_check_jobs: 1`n"'
  - ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_warning_level: 0`n"'
  - ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_system_verbose: false`n"'

build_script:
  - mkdir build
  - mkdir build\bin
  - mkdir build\bin\Release
  - cd build
  #- cmd: 'echo local_settings: > cppan.yml'
  #- cmd: 'echo     generator: %generator% >> cppan.yml'
  #- cmd: 'echo     use_shared_libs: true >> cppan.yml'
  #- cppan --build ..
  - cmake .. -G "%generator%"
  - cmake --build . --config Release

artifacts:
  - path: build\bin\Release
  #- path: build
    name: tesseract-$(APPVEYOR_BUILD_VERSION)
    
