environment:
  matrix:
    # not working for some reason now
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #platform: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: Win64

configuration:
  - Release

cache:
  - c:/Users/appveyor/.sw
  - .sw

before_build:
  - curl -fsS -L -o dl.zip https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-windows-client.zip
  - 7z x dl.zip
  - set PATH=%PATH%;%cd%

build_script:
  - sw -platform %platform% build

after_build:
  - 7z a tesseract.zip %APPVEYOR_BUILD_FOLDER%\.sw\windows_*_msvc_*_shared_Release_*\*.exe %APPVEYOR_BUILD_FOLDER%\.sw\windows_*_msvc_*_shared_Release_*\*.dll

artifacts:
  - path: tesseract.zip
    name: tesseract-$(APPVEYOR_BUILD_VERSION)
