name: dailycmake

on:
  schedule:
    # every day at 2:15 AM UTC
    - cron: 15 2 * * *

jobs:
  gcc-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]
        gcc_version: [ 11, 10, 9, 8, 7, 6, 5 ]

    steps:
      - name: Install compiler
        run: |
          sudo apt-get install -y gcc-${{ matrix.gcc_version }} g++-${{ matrix.gcc_version }}
          
      - name: Install dependencies
        run: sudo apt-get install libleptonica-dev libpango1.0-dev cabextract -y

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          export CC=gcc-${{ matrix.gcc_version }}
          export CXX=g++-${{ matrix.gcc_version }}
          
      - name: Configure
        run: |
             mkdir build && cd build
             cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_BUILD_TYPE=Debug ..
        
      - name: Build
        run: cmake --build build --config Debug

  clang-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        clang_version: [ 10, 9, 8, 7, 6 ]

    steps:
      - name: Install compiler
        run: |
          sudo apt-get install -y clang-${{ matrix.clang_version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          export CC=clang-${{ matrix.clang_version }}
          export CXX=clang++-${{ matrix.clang_version }}
          cmake -D BUILD_TESTS=ON ./
          make
          ./test/etl_tests

    steps:
    - uses: actions/checkout@v2

        

      
      
    - name: autoconf
      run: ./autogen.sh

    - name: configure
      run: ./configure --enable-openmp --disable-shared --disable-debug --disable-opencl --disable-graphics --disable-legacy --with-tensorflow=no 'CXXFLAGS=-g -O2 -Wall -Wextra -Wpedantic -fsanitize=address,undefined -fstack-protector-strong -ftrapv'
      
    - name: make
      run: make training -j 8
      
    - name: make check
      run: make check -j 4
      
    - name: display test report
      run: git log -1 && cat unittest/test-suite.log
      if: success() || failure()
      
