name: dailycmake

on:
  schedule:
    # every day at 2:15 AM UTC
    - cron: 15 2 * * *

jobs:
  build-gcc-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        gcc_version: [ 10, 9, 8, 7, 6, 5 ]
        build_type: [ Release, Debug ]
        exclude:
             - { gcc_version: 5, os: ubuntu-20.04 }
             - { gcc_version: 6, os: ubuntu-20.04 }

    steps:
      - name: Install compiler
        run: |
          sudo apt-get install -y gcc-${{ matrix.gcc_version }} g++-${{ matrix.gcc_version }}
          
      - name: Install dependencies
        run: sudo apt-get install libleptonica-dev libpango1.0-dev -y

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          export CC=gcc-${{ matrix.gcc_version }}
          export CXX=g++-${{ matrix.gcc_version }}
          
      - name: Configure
        run: |
             mkdir build && cd build
             cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

  build-clang-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        gcc_version: [ 11, 10, 9, 8, 7, 6, 5, 4 ]
        build_type: [ Release, Debug ]

    steps:
      - name: Install compiler
        run: |
          sudo apt-get install -y clang-${{ matrix.clang_version }}

      - name: Install dependencies
        run: sudo apt-get install libleptonica-dev libpango1.0-dev -y

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          export CC=gcc-${{ matrix.clang_version }}
          export CXX=g++-${{ matrix.clang_version }}
          
      - name: Configure
        run: |
             mkdir build && cd build
             cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
        
                               
